application: mistry-nest-controlbot
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.(js))
  static_files: static/\1
  upload: static/(.*\.(js))

# main will look for a replacement in blobstore, if not, will redirect to
# static/
- url: /([^/]+\.(gif|png|jpg|ico))
  script: main.APPLICATION

- url: /static/([^/]+\.(gif|png|jpg|ico))
  static_files: static/\1
  upload: static/([^/]+\.(gif|png|jpg|ico))

- url: /stylesheets
  static_dir: stylesheets

- url: /templates
  script: templates

- url: /.*
  script: main.APPLICATION


# Search DEFAULT_SKIP_FILES in google.appengine.api.appinfo plus a few others
skip_files: |
    ^(.*/)?(
    (app\.yaml)|
    (app\.yml)|
    (#.*#)|
    (.*~)|
    (.*\.py[co])|
    (.*/RCS/.*)|
    (\..*)|
    (tests/.*)|
    (tools/.*)|
    ([A-Z]+(\.py)?)|
    (Makefile)|
    (.*\.rej)|
    (.*\.orig)|
    )$
